# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-09 05:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='content',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
    ]
