# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-09 06:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_section_content'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Snippet',
            new_name='Block',
        ),
        migrations.RenameField(
            model_name='block',
            old_name='code',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='section',
            name='content',
        ),
    ]
