# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-09 06:43
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20170709_0625'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='block',
            name='section',
        ),
        migrations.AddField(
            model_name='section',
            name='content',
            field=tinymce.models.HTMLField(default=' '),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Block',
        ),
    ]
