# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-07-09 10:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20170709_0643'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='next_chapter',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chapter_next', to='core.Chapter'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='previous_chapter',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Chapter'),
        ),
    ]
